"""US-SUPP-008 add purchase order receiving fields

Revision ID: 27a37f4cd6d2
Revises: 66d999e4097c
Create Date: 2026-07-29 11:51:32.160729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a37f4cd6d2'
down_revision = '66d999e4097c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_received', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discrepancy_reason', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('discrepancy_notes', sa.Text(), nullable=True))

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('received_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_column('received_at')

    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_column('discrepancy_notes')
        batch_op.drop_column('discrepancy_reason')
        batch_op.drop_column('quantity_received')
    # ### end Alembic commands ###
