"""US-INV-005 Add inventory_value_history table for value tracking

Revision ID: 31e5d07e5229
Revises: 3e515d718137
Create Date: 2025-11-14 14:35:06.985686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31e5d07e5229'
down_revision = '3e515d718137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_value_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_products', sa.Integer(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('categories_count', sa.Integer(), nullable=False),
    sa.Column('trigger_reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_value_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_value_history_snapshot_date'), ['snapshot_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_value_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_value_history_snapshot_date'))

    op.drop_table('inventory_value_history')
    # ### end Alembic commands ###
