"""US-PROD-006: Add soft delete and audit table for products

Revision ID: 32c1e176d214
Revises: 9f4fd504acd5
Create Date: 2025-11-04 10:59:43.894570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c1e176d214'
down_revision = '9f4fd504acd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_deletion_audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('product_data', sa.JSON(), nullable=False),
    sa.Column('deleted_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_deletion_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_deletion_audits_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('product_deletion_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_deletion_audits_product_id'))

    op.drop_table('product_deletion_audits')
    # ### end Alembic commands ###
