"""US-INV-001: Add real-time stock tracking fields (stock_last_updated, last_updated_by_id, version)

Revision ID: 3488fe0cb2be
Revises: 91a1b0ade10f
Create Date: 2025-11-08 11:05:57.100465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3488fe0cb2be'
down_revision = '91a1b0ade10f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_last_updated', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated_by_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_foreign_key('fk_products_last_updated_by', 'users', ['last_updated_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_last_updated_by', type_='foreignkey')
        batch_op.drop_column('version')
        batch_op.drop_column('last_updated_by_id')
        batch_op.drop_column('stock_last_updated')

    # ### end Alembic commands ###
