"""US-PROD-008: Agregar campo reorder_point a productos

Revision ID: 91a1b0ade10f
Revises: 32c1e176d214
Create Date: 2025-11-04 19:06:26.414178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a1b0ade10f'
down_revision = '32c1e176d214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # US-PROD-008 CA-1: Agregar campo reorder_point con valor por defecto 10
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reorder_point', sa.Integer(), nullable=False, server_default='10'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('reorder_point')

    # ### end Alembic commands ###
