"""US-CUST-009 Add customer_notes table

Revision ID: 94472240294a
Revises: f5a2c9d3b8e1
Create Date: 2026-02-20 11:54:17.068410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94472240294a'
down_revision = 'f5a2c9d3b8e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_important', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_notes', schema=None) as batch_op:
        batch_op.create_index('ix_customer_notes_customer_created', ['customer_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_notes_customer_id'), ['customer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_notes_customer_id'))
        batch_op.drop_index('ix_customer_notes_customer_created')

    op.drop_table('customer_notes')
    # ### end Alembic commands ###
