"""US-SUPP-010 add purchase order edit audit

Revision ID: 9b29156e5ee0
Revises: 27a37f4cd6d2
Create Date: 2026-07-29 12:09:01.200652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b29156e5ee0'
down_revision = '27a37f4cd6d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_order_edit_audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=36), nullable=False),
    sa.Column('edited_by_id', sa.String(length=36), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['edited_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order_edit_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_edit_audits_purchase_order_id'), ['purchase_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_edit_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_edit_audits_purchase_order_id'))

    op.drop_table('purchase_order_edit_audits')
    # ### end Alembic commands ###
